/* Generated by CM v2 compiler — do not edit */
#include "cm/core.h"
#include "cm/memory.h"
#include "cm/string.h"
#include "cm/safe_ptr.h"
#include "cm/option.h"
#include "cm/result.h"
#include "cm/http.h"
#include <stdio.h>
#include <stdlib.h>

void cm_main()
{
    const int cm_x = 10;
    const int cm_y = 20;
    int cm_z = (cm_x + cm_y);
    const cm_string_t* cm_s = cm_string_new("adham");
    cm_println(cm_string_new("Hello, CM v2!"));
    cm_println(cm_s);
    cm_println(cm_string_new("X+Y="));
    cm_println(cm_z);
    if ((cm_z > 10)) {
        cm_println(cm_string_new("z is greater than 10"));
    } else {
        cm_println(cm_string_new("z is less than or equal to 10"));
    }
    int cm_i = 0;
    while ((cm_i < 10)) {
        cm_println(cm_i);
        cm_i = (cm_i + 1);
    }
    while ((cm_z > 10)) {
        cm_println(cm_z);
        cm_z = (cm_z - 1);
    }
    { /* match */
        int _cm_match_0 = (int)(cm_z);
        if (10 == _cm_match_0) {
            cm_println(cm_string_new("z is 10"));
        }
        else if (20 == _cm_match_0) {
            cm_println(cm_string_new("z is 20"));
        }
        else {
            cm_println(cm_string_new("z is neither 10 nor 20"));
        }
    } /* end match */
}


int main(int argc, char** argv) {
    (void)argc; (void)argv;
    cm_gc_init();
    cm_main();
    cm_gc_shutdown();
    return 0;
}
